In [2]:
import numpy as np

X = np.array([1,2])
X.shape

(2,)

In [4]:
W = np.array([[1, 3, 5],[2, 4, 6]])
print(W)
W.shape

[[1 3 5]
 [2 4 6]]


(2, 3)

In [6]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]


## 행렬의 곱으로 입력값과 가중치의 계산을 한꺼번에 가능하다.

In [10]:
X = np.array([1,5])
W1 = np.array([[1,2,3],[4,5,6]])
W2 = np.array([[2,3],[5,6],[3,4]])

In [11]:
first = np.dot(X,W1)

In [12]:
print(first)
first.shape

[21 27 33]


(3,)

In [13]:
second = np.dot(first,W2)

In [14]:
print(second)
second.shape

[276 357]


(2,)

## 적은 코드만으로 위와 같이 3층 신경망을 구현할 수 있다.

## 1층에서 2층으로 가는 신호

In [19]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

X = np.array([1,2])
W1 = np.array([[1,2,3],[2,3,4]])
B = np.array([3])

In [21]:
first = np.dot(X,W1) 
print(first)

[ 5  8 11]


In [22]:
first += B

In [23]:
print(first)

[ 8 11 14]


In [24]:
first_fun = sigmoid(first)

In [25]:
print(first_fun)

[0.99966465 0.9999833  0.99999917]


In [26]:
W2 = np.array([[1,2],[2,3],[3,4]])
B2 = np.array([1])

In [28]:
second = np.dot(first_fun, W2)
second += B2

In [29]:
print(second)

[6.99962875 9.99927587]


In [30]:
second_fun = sigmoid(second)

In [31]:
print(second_fun)

[0.99908861 0.99995457]


In [35]:
def identity_function(x):
    return x

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2, 0.5, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

In [36]:
network = init_network()

In [37]:
x = np.array([[1.0,0.5]])
y = forward(network,x)

In [38]:
print(y)

[[0.31707227 0.69682092]]


## 소프트맥스 함수의 구현

In [39]:
a = np.array([0.3,2.9,4.0])
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [40]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [41]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [42]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

## 개선된 소프트맥스 함수의 구현

In [45]:
def softmax(a):
    max_a = np.max(a)
    exp_a = np.exp(a - max_a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [46]:
a = np.array([1,2,3])
print(softmax(a))

[0.09003057 0.24472847 0.66524096]
